### ISSUE TITLE
Replace NodeXML asString(), asDouble(), asInt() by a common unwrap() method.

### ISSUE THREAD

**Issue by ducdetronquito** [johnBuffer/MicroXML#1]
I don't know if it's possible in C++ and if it is a good C++ practice, but it good be cool to replace 
- `NodeXML::asString()`
- `NodeXML::asDouble()`
- `NodeXML::asInt()`

by a unique method `NodeXML::unwrap()` (or a method with a different name).

It seems more concise :ok_hand: 

What is your opinion on this ?

**Comment by johnBuffer** [comment]
Indeed, it would be more concise :) However, I think its signature must vary one way or another in order to deduce the return type of unwrap - and the corresponding parse function unwrap is meant to call. Plus, it would be hard for the unwrap function to guess what to do with the data (string, double, int...?). For example, if the user wanted a string with value "123", it would be impossible for the function to deduce it. In my opinion, it is the final user's responsibility to clearly indicate the desired cast type.

**Comment by ducdetronquito** [comment]
Right ! :+1:
Seems to be the same behaviour with [pugixml](https://github.com/zeux/pugixml) and [tinyxml2](https://github.com/leethomason/tinyxml2) anyway ^^
